// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App Wails 后端服务结构（v3 经 application.NewService 注册为绑定服务）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelTask 取消任务（1 秒内生效）。
 */
export function CancelTask(taskID: string): $CancellablePromise<$models.Result> {
    return $Call.ByID(840985698, taskID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ConsumePendingOpenFile 前端挂载后拉取并清空暂存的清单路径（无暂存时 Path 为空）。
 */
export function ConsumePendingOpenFile(): $CancellablePromise<$models.Result> {
    return $Call.ByID(35671518).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CopyText 复制文本到剪贴板。
 */
export function CopyText(text: string): $CancellablePromise<$models.Result> {
    return $Call.ByID(2798394763, text).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ExportCSV 导出任务结果为 CSV（带 UTF-8 BOM）。onlyFailed 时仅导出
 * 校验不一致/缺失项（批量校验的一键导出不一致项）。
 */
export function ExportCSV(taskID: string, path: string, onlyFailed: boolean): $CancellablePromise<$models.Result> {
    return $Call.ByID(4049822517, taskID, path, onlyFailed).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ExportSUM 导出任务结果为标准 SUM 格式清单（可被批量校验重新导入，闭环）。
 */
export function ExportSUM(taskID: string, path: string, algo: string): $CancellablePromise<$models.Result> {
    return $Call.ByID(2054194126, taskID, path, algo).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetFileAssocStatus 当前关联到本应用的扩展名数量（前端开关的勾选依据）。
 */
export function GetFileAssocStatus(): $CancellablePromise<$models.Result> {
    return $Call.ByID(922682546).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PickFiles 多选文件对话框。
 */
export function PickFiles(title: string): $CancellablePromise<$models.Result> {
    return $Call.ByID(4162647679, title).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PickFolder 选择文件夹（递归计算）。
 */
export function PickFolder(title: string): $CancellablePromise<$models.Result> {
    return $Call.ByID(1618095492, title).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PickManifestFile 选择哈希清单文件。
 */
export function PickManifestFile(title: string): $CancellablePromise<$models.Result> {
    return $Call.ByID(1008734915, title).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PickSavePath 导出保存对话框。
 */
export function PickSavePath(defaultName: string, filterName: string, pattern: string, title: string): $CancellablePromise<$models.Result> {
    return $Call.ByID(2127023646, defaultName, filterName, pattern, title).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RegisterFileAssociations 显式注册全部清单扩展名关联（被其他程序占用的跳过），
 * Count 为实际写入数量。
 */
export function RegisterFileAssociations(): $CancellablePromise<$models.Result> {
    return $Call.ByID(349570046).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetAlwaysOnTop 切换主窗口置顶（前端顶栏图钉按钮）。
 */
export function SetAlwaysOnTop(on: boolean): $CancellablePromise<$models.Result> {
    return $Call.ByID(3581063306, on).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetupResultContextMenu （重）建结果行右键菜单：应用启动与每次切换语言时由前端调用。
 */
export function SetupResultContextMenu(labels: $models.ContextMenuLabels): $CancellablePromise<$models.Result> {
    return $Call.ByID(3415215169, labels).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StartHashTask 启动哈希计算任务（异步），立即返回 taskId。
 * 目录展开在任务 goroutine 内进行（ExpandPathsDetailedContext）：超大目录树
 * 不再阻塞绑定调用，扫描期间经 hash:progress 的 scanning 标记上报已发现文件数，
 * 且随 CancelTask 可取消；展开完成后总量才确定，经后续进度/完成事件下发。
 * 进度/结果通过 hash:progress / hash:items / hash:done 事件推送。
 */
export function StartHashTask(paths: string[], algos: string[]): $CancellablePromise<$models.Result> {
    return $Call.ByID(933405966, paths, algos).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StartVerifyTask 启动批量校验任务：解析清单 → 识别算法 → 以基准目录解析
 * 相对路径 → 批量计算并逐一对比。baseDir 为空时取清单所在目录。
 */
export function StartVerifyTask(manifestPath: string, baseDir: string): $CancellablePromise<$models.Result> {
    return $Call.ByID(2904902583, manifestPath, baseDir).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UnregisterFileAssociations 解除关联：只删除本应用自有 ProgID 条目，
 * Count 为实际删除的扩展名数量。
 */
export function UnregisterFileAssociations(): $CancellablePromise<$models.Result> {
    return $Call.ByID(724829789).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Result.createFrom;
