// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppError 结构化错误：错误码 + 中英双语信息，前端按当前语言展示，禁止 panic 与静默吞错。
 */
export class AppError {
    "code": string;
    "zh": string;
    "en": string;
    "detail"?: string;

    /** Creates a new AppError instance. */
    constructor($$source: Partial<AppError> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("zh" in $$source)) {
            this["zh"] = "";
        }
        if (!("en" in $$source)) {
            this["en"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppError instance from a string or object.
     */
    static createFrom($$source: any = {}): AppError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppError($$parsedSource as Partial<AppError>);
    }
}

/**
 * Result 绑定方法统一返回结构（对话框选择、任务启动、导出等）。
 */
export class Result {
    "ok": boolean;
    "error"?: AppError | null;

    /**
     * 多选路径
     */
    "paths"?: string[];

    /**
     * 单选路径
     */
    "path"?: string;

    /**
     * 任务 ID
     */
    "taskId"?: string;

    /**
     * 条目总数
     */
    "total": number;

    /**
     * 总字节数
     */
    "totalBytes": number;

    /**
     * 批量校验识别出的算法
     */
    "algo"?: string;

    /**
     * 任务先异步扫描目录，总量经后续进度事件下发
     */
    "scanning"?: boolean;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField2_0($$parsedSource["paths"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

// Private type creation functions
const $$createType0 = AppError.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
