// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function ExportCSV(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportCSV'](arg1, arg2, arg3);
}

export function ExportSUM(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportSUM'](arg1, arg2, arg3);
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickManifestFile() {
  return window['go']['main']['App']['PickManifestFile']();
}

export function PickSavePath(arg1, arg2, arg3) {
  return window['go']['main']['App']['PickSavePath'](arg1, arg2, arg3);
}

export function StartHashTask(arg1, arg2) {
  return window['go']['main']['App']['StartHashTask'](arg1, arg2);
}

export function StartVerifyTask(arg1, arg2) {
  return window['go']['main']['App']['StartVerifyTask'](arg1, arg2);
}
