// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelTask(arg1:string):Promise<main.Result>;

export function CopyText(arg1:string):Promise<main.Result>;

export function ExportCSV(arg1:string,arg2:string,arg3:boolean):Promise<main.Result>;

export function ExportSUM(arg1:string,arg2:string,arg3:string):Promise<main.Result>;

export function PickFiles():Promise<main.Result>;

export function PickFolder():Promise<main.Result>;

export function PickManifestFile():Promise<main.Result>;

export function PickSavePath(arg1:string,arg2:string,arg3:string):Promise<main.Result>;

export function StartHashTask(arg1:Array<string>,arg2:Array<string>):Promise<main.Result>;

export function StartVerifyTask(arg1:string,arg2:string):Promise<main.Result>;
